/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "GreenThrottle_autodefs.h"
#include "s3eEdk.h"
#include "GreenThrottle.h"
//Declarations of Init and Term functions
extern s3eResult GreenThrottleInit();
extern void GreenThrottleTerminate();


void GreenThrottleRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[12];
    funcPtrs[0] = (void*)GetButtonState;
    funcPtrs[1] = (void*)GetAnalogState;
    funcPtrs[2] = (void*)GetAnalogChanged;
    funcPtrs[3] = (void*)GetConnectedState;
    funcPtrs[4] = (void*)GetServiceConnected;
    funcPtrs[5] = (void*)ClearControllerState;
    funcPtrs[6] = (void*)AddLeftButtonRemap;
    funcPtrs[7] = (void*)RemoveLeftButtonRemap;
    funcPtrs[8] = (void*)AddRightButtonRemap;
    funcPtrs[9] = (void*)RemoveRightButtonRemap;
    funcPtrs[10] = (void*)HideAndroidSystemUI;
    funcPtrs[11] = (void*)StartFrame;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[12] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("GreenThrottle", funcPtrs, sizeof(funcPtrs), flags, GreenThrottleInit, GreenThrottleTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int GreenThrottleStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&GreenThrottleRegisterExt;
    return 0;
}

int g_GreenThrottleVal = GreenThrottleStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    GreenThrottleRegisterExt();
}
#endif

#endif
