/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef GREENTHROTTLE_AUTODEFS_H
#define GREENTHROTTLE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GREENTHROTTLE_NAME "GreenThrottle"
#define S3E_EXT_GREENTHROTTLE_HASH 0xd152840c

#endif /* !GREENTHROTTLE_AUTODEFS_H */
